# Generated by Django 3.0.7 on 2020-07-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyRestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='name',
            new_name='Name',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyRestApp.Emp')),
            ],
        ),
    ]
